#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dill
Version  : 0.3.3
Release  : 1
URL      : https://files.pythonhosted.org/packages/0d/5a/0534e0eb113be5635a6bd5e8b22ddf780cf977a403155fd4e07e6b92fb3d/dill-0.3.3.zip
Source0  : https://files.pythonhosted.org/packages/0d/5a/0534e0eb113be5635a6bd5e8b22ddf780cf977a403155fd4e07e6b92fb3d/dill-0.3.3.zip
Summary  : serialize all of python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: dill-bin = %{version}-%{release}
Requires: dill-license = %{version}-%{release}
Requires: dill-python = %{version}-%{release}
Requires: dill-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
-----------------------------
dill: serialize all of python
-----------------------------

%package bin
Summary: bin components for the dill package.
Group: Binaries
Requires: dill-license = %{version}-%{release}

%description bin
bin components for the dill package.


%package license
Summary: license components for the dill package.
Group: Default

%description license
license components for the dill package.


%package python
Summary: python components for the dill package.
Group: Default
Requires: dill-python3 = %{version}-%{release}

%description python
python components for the dill package.


%package python3
Summary: python3 components for the dill package.
Group: Default
Requires: python3-core
Provides: pypi(dill)

%description python3
python3 components for the dill package.


%prep
%setup -q -n dill-0.3.3
cd %{_builddir}/dill-0.3.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1614041462
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dill
cp %{_builddir}/dill-0.3.3/LICENSE %{buildroot}/usr/share/package-licenses/dill/320da450bde36a71a468cc6b239829612c88c991
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/get_objgraph
/usr/bin/undill

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dill/320da450bde36a71a468cc6b239829612c88c991

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
